// Spectrum Saver build configuration for the bundled google/crc32c sources.
// This replaces the equivalent header generated by google/crc32c's CMake build.

#ifndef CRC32C_CRC32C_CONFIG_H_
#define CRC32C_CRC32C_CONFIG_H_

#if defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__)
#define BYTE_ORDER_BIG_ENDIAN (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#elif defined(_WIN32)
#define BYTE_ORDER_BIG_ENDIAN 0
#else
#error "Unable to determine target byte order for google/crc32c"
#endif

#if defined(__GNUC__) || defined(__clang__)
#define HAVE_BUILTIN_PREFETCH 1
#else
#define HAVE_BUILTIN_PREFETCH 0
#endif

#if defined(__x86_64__) || defined(_M_X64)
#define HAVE_MM_PREFETCH 1
#define HAVE_SSE42 1
#else
#define HAVE_MM_PREFETCH 0
#define HAVE_SSE42 0
#endif

#if defined(__aarch64__) || defined(_M_ARM64)
#define HAVE_ARM64_CRC32C 1
#else
#define HAVE_ARM64_CRC32C 0
#endif

// A weak getauxval declaration keeps Linux ARM builds compatible with systems
// where the function is unavailable while still enabling runtime dispatch when
// libc provides it.
#if defined(__linux__) && (defined(__GNUC__) || defined(__clang__))
#define HAVE_STRONG_GETAUXVAL 0
#define HAVE_WEAK_GETAUXVAL 1
#else
#define HAVE_STRONG_GETAUXVAL 0
#define HAVE_WEAK_GETAUXVAL 0
#endif

#define CRC32C_TESTS_BUILT_WITH_GLOG 0

#endif  // CRC32C_CRC32C_CONFIG_H_
